### ISSUE TITLE
Make file urls amenable to the scorer

### ISSUE THREAD

**Issue by sven-nm** [hipe-eval/HIPE-scorer#20]
Feature request : because all the modules in [HIPE-pycommons](https://github.com/hipe-eval/HIPE-pycommons) can be called either with a path or an url, I think the scorer should too. Adding a simple 

```python
import urllib
if url:
    response = urllib.request.urlopen(url)
    tsv_data = response.read().decode('utf-8')
```

Would do the job !

**Comment by simon-clematide** [comment]
Good point. I would suggest that we just use https://github.com/RaRe-Technologies/smart_open's open in the code, and then we have a very general solution, in whichever way the input files are specified. Agreed?

**Comment by simon-clematide** [comment]
Part of the code already used smart open. Now its done.
